enum TipoStatusTurno {
    TRABALHANDO = "TRABALHANDO",
    INTERVALO = "INTERVALO",
    ENCERRADO = "ENCERRADO",
    NAO_COMPARECEU = "NAO_COMPARECEU",
    IRREGULAR = "IRREGULAR"
}

export default TipoStatusTurno;